import type { Category, Product } from "./types";

export const fallbackCategories: Category[] = [
  {
    id: 1,
    slug: "dashcam",
    name: "دوربین ثبت وقایع خودرو",
    description:
      "دوربین‌های جلو و عقب برای ثبت مسیر، اتفاقات رانندگی و آرامش بیشتر پشت فرمان.",
    parent: 0,
    count: 2,
    children: [],
  },
  {
    id: 2,
    slug: "helmet-gear",
    name: "تجهیزات کلاه کاسکت",
    description:
      "اینترکام، بلوتوث و دوربین کلاه برای ارتباط، موسیقی و ثبت مسیر هنگام موتورسواری.",
    parent: 0,
    count: 0,
    children: [],
  },
  {
    id: 3,
    slug: "bluetooth-intercom",
    name: "بلوتوث و اینترکام",
    description: "ارتباط گروهی، تماس و موسیقی با اینترکام‌های مخصوص کلاه کاسکت.",
    parent: 2,
    count: 1,
    children: [],
  },
  {
    id: 4,
    slug: "camera-intercom",
    name: "اینترکام دوربین‌دار",
    description: "ترکیب اینترکام، هندزفری بلوتوث و دوربین ثبت مسیر در یک دستگاه.",
    parent: 2,
    count: 1,
    children: [],
  },
];

const dashcam = { id: 1, slug: "dashcam", name: "دوربین ثبت وقایع خودرو" };
const helmet = { id: 2, slug: "helmet-gear", name: "تجهیزات کلاه کاسکت" };
const bluetooth = { id: 3, slug: "bluetooth-intercom", name: "بلوتوث و اینترکام" };
const cameraIntercom = { id: 4, slug: "camera-intercom", name: "اینترکام دوربین‌دار" };

export const fallbackProducts: Product[] = [
  {
    id: 1,
    slug: "azdome-m17-pro",
    name: "دوربین ثبت وقایع دو لنز AZDOME M17 Pro",
    brand: "AZDOME",
    model: "M17 Pro",
    sku: "",
    price: null,
    regularPrice: null,
    stockStatus: "unknown",
    stockQuantity: null,
    image: { src: "/images/dashcam-device.jpg", alt: "دوربین ثبت وقایع روی سطح روشن" },
    gallery: [
      { src: "/images/dashcam-device.jpg", alt: "دوربین ثبت وقایع روی سطح روشن" },
      { src: "/images/dashcam-road.jpg", alt: "نمای جاده از پشت شیشه خودرو" },
    ],
    shortDescription:
      "دوربین ثبت وقایع AZDOME M17 Pro با دو دوربین جلو و عقب، برای ثبت مسیر، اتفاقات رانندگی و افزایش امنیت خودرو طراحی شده است. این محصول با امکاناتی مانند اتصال به موبایل، سنسور ضربه، ضبط مداوم و حالت پارکینگ، گزینه‌ای کاربردی برای استفاده روزمره است.",
    description:
      "دوربین ثبت وقایع AZDOME M17 Pro با دو دوربین جلو و عقب، برای ثبت مسیر، اتفاقات رانندگی و افزایش امنیت خودرو طراحی شده است. اتصال به موبایل، سنسور ضربه، ضبط مداوم و حالت پارکینگ آن را برای استفاده روزمره مناسب می‌کند.",
    specs: [],
    features: [
      "دارای دوربین جلو و عقب",
      "زاویه دید گسترده",
      "نمایشگر داخلی",
      "اتصال Wi-Fi",
      "اتصال به اپلیکیشن موبایل",
      "سنسور ضربه G-Sensor",
      "قابلیت Loop Recording",
      "حالت Parking Mode",
      "ضبط صدا",
      "پشتیبانی از کارت حافظه",
      "اتصال Type-C",
    ],
    boxContents: [],
    warranty: "",
    shippingStatus: "",
    note: "مدل M17 Pro در نسخه‌های مختلف عرضه شده است. کیفیت دقیق فیلم‌برداری، ظرفیت کارت حافظه داخل بسته، GPS، ADAS، نوع Wi-Fi و مشخصات دوربین عقب باید از روی جعبه محصول موجود در انبار بررسی و سپس در مشخصات نهایی ثبت شود.",
    categories: [dashcam],
    modified: "2026-09-13T00:00:00.000Z",
  },
  {
    id: 2,
    slug: "lingdu-d08",
    name: "دوربین ثبت وقایع Lingdu D08",
    brand: "Lingdu",
    model: "D08",
    sku: "",
    price: null,
    regularPrice: null,
    stockStatus: "unknown",
    stockQuantity: null,
    image: { src: "/images/dashcam-road.jpg", alt: "ثبت مسیر از روی شیشه جلو" },
    gallery: [{ src: "/images/dashcam-road.jpg", alt: "ثبت مسیر از روی شیشه جلو" }],
    shortDescription:
      "Lingdu D08 یک دوربین ثبت وقایع جمع‌وجور و کاربردی برای ثبت اتفاقات رانندگی است که امکان اتصال به تلفن همراه از طریق Wi-Fi را دارد و تصاویر را با کیفیت مناسب ضبط می‌کند.",
    description:
      "Lingdu D08 یک دوربین ثبت وقایع جمع‌وجور برای ثبت اتفاقات رانندگی است. این مدل به تلفن همراه وصل می‌شود و برای استفاده روزمره طراحی شده است.",
    specs: [
      { label: "کیفیت فیلم‌برداری", value: "1296P" },
      { label: "نرخ فیلم‌برداری", value: "۳۰ فریم بر ثانیه" },
      { label: "نوع دوربین", value: "تک لنز جلو" },
      { label: "سنسور تصویر", value: "۲ مگاپیکسل" },
      { label: "دیافراگم", value: "F/2.0" },
      { label: "اتصال", value: "Wi-Fi داخلی و اپلیکیشن موبایل" },
      { label: "درگاه", value: "Type-C" },
      { label: "کارت حافظه", value: "MicroSD تا ۱۲۸ گیگابایت" },
      { label: "سنسور ضربه", value: "G-Sensor" },
      { label: "ضبط مداوم", value: "Loop Recording" },
      { label: "صدا", value: "میکروفون و اسپیکر" },
      { label: "حالت پارک", value: "Parking Mode و Time-Lapse" },
      { label: "زاویه دید", value: "حدود ۱۲۲ درجه، طبق مشخصات سازنده" },
    ],
    features: [
      "فیلم‌برداری 1296P",
      "اتصال Wi-Fi به موبایل",
      "G-Sensor و Loop Recording",
      "Parking Mode با Time-Lapse",
    ],
    boxContents: [],
    warranty: "",
    shippingStatus: "",
    note: "زاویه دید طبق مشخصات سازنده حدود ۱۲۲ درجه است. پیش از نهایی شدن اطلاعات روی سایت، مشخصات روی جعبه موجودی بررسی شود.",
    categories: [dashcam],
    modified: "2026-09-13T00:00:00.000Z",
  },
  {
    id: 3,
    slug: "maxto-m6s",
    name: "اینترکام و بلوتوث کلاه کاسکت Maxto M6S",
    brand: "Maxto",
    model: "M6S",
    sku: "",
    price: null,
    regularPrice: null,
    stockStatus: "unknown",
    stockQuantity: null,
    image: { src: "/images/helmet-intercom.jpg", alt: "اینترکام نصب‌شده روی کلاه کاسکت" },
    gallery: [{ src: "/images/helmet-intercom.jpg", alt: "اینترکام نصب‌شده روی کلاه کاسکت" }],
    shortDescription:
      "Maxto M6S یک اینترکام حرفه‌ای برای موتورسواران است که امکان برقراری ارتباط گروهی، تماس تلفنی، گوش دادن به موسیقی و استفاده از امکانات بلوتوث را هنگام موتورسواری فراهم می‌کند.",
    description:
      "Maxto M6S برای ارتباط گروهی، تماس، موسیقی و دستیار صوتی هنگام موتورسواری ساخته شده است. چیپ Qualcomm، کاهش نویز و استاندارد IP67 آن را برای استفاده در مسیر مناسب می‌کند.",
    specs: [
      { label: "بلوتوث", value: "Bluetooth 5.0" },
      { label: "چیپ", value: "Qualcomm" },
      { label: "ارتباط گروهی", value: "تا ۸ موتورسوار" },
      { label: "برد ارتباطی", value: "حدود ۱۰۰۰ متر" },
      { label: "اتصال گروه", value: "اتصال مجدد خودکار اعضا" },
      { label: "موسیقی", value: "Music Sharing" },
      { label: "کاهش نویز", value: "DSP / CVC" },
      { label: "رادیو", value: "FM" },
      { label: "دستیار صوتی", value: "اتصال به دستیار صوتی موبایل" },
      { label: "تماس", value: "پاسخ خودکار" },
      { label: "مقاومت", value: "ضدآب IP67" },
      { label: "شارژدهی", value: "حدود ۱۵ ساعت استفاده" },
      { label: "آماده‌به‌کار", value: "حدود ۲۰۰ ساعت" },
      { label: "زمان شارژ", value: "حدود ۲.۵ ساعت" },
    ],
    features: [
      "ارتباط گروهی تا ۸ موتورسوار",
      "برد حدود ۱۰۰۰ متر",
      "Music Sharing",
      "رادیو FM",
      "استاندارد IP67",
    ],
    boxContents: [],
    warranty: "",
    shippingStatus: "",
    note: "مناسب کلاه Full Face، Flip Up، Modular و Motocross.",
    categories: [helmet, bluetooth],
    modified: "2026-09-13T00:00:00.000Z",
  },
  {
    id: 4,
    slug: "maxto-m3s",
    name: "اینترکام و دوربین کلاه کاسکت Maxto M3S",
    brand: "Maxto",
    model: "M3S",
    sku: "",
    price: null,
    regularPrice: null,
    stockStatus: "unknown",
    stockQuantity: null,
    image: { src: "/images/helmet-camera.jpg", alt: "دوربین روی کلاه کاسکت" },
    gallery: [
      { src: "/images/helmet-camera.jpg", alt: "دوربین روی کلاه کاسکت" },
      { src: "/images/helmet-ride.jpg", alt: "موتورسوار با کلاه کاسکت" },
    ],
    shortDescription:
      "Maxto M3S یک محصول چندکاره برای موتورسواران است که بلوتوث، اینترکام و دوربین ثبت مسیر را در یک دستگاه ارائه می‌دهد. این محصول علاوه بر امکان ارتباط با سایر موتورسواران، قابلیت فیلم‌برداری از مسیر را نیز دارد.",
    description:
      "Maxto M3S عملاً ترکیبی از سه محصول است: دوربین، اینترکام و هندزفری بلوتوث. موتورسوار می‌تواند هم‌زمان با گروه در ارتباط باشد و مسیر را هم ضبط کند.",
    specs: [
      { label: "فیلم‌برداری", value: "2K / 1440P" },
      { label: "لنز", value: "Sony" },
      { label: "زاویه دید", value: "حدود ۱۲۰ درجه" },
      { label: "دیافراگم", value: "F2.0" },
      { label: "لرزش‌گیر", value: "دارد" },
      { label: "ضبط مداوم", value: "Loop Recording" },
      { label: "عکاسی", value: "دارد" },
      { label: "اتصال تصویر", value: "Wi-Fi و اپلیکیشن RICAM" },
      { label: "ارتباط گروهی", value: "تا ۶ موتورسوار" },
      { label: "برد ارتباطی", value: "تا حدود ۱۰۰۰ متر" },
      { label: "بلوتوث", value: "Bluetooth 5.0" },
      { label: "کاهش نویز", value: "CVC" },
      { label: "رادیو", value: "FM" },
      { label: "جفت‌سازی", value: "Universal Pairing" },
      { label: "سازگاری", value: "قابل اتصال به بعضی اینترکام‌های برندهای دیگر" },
      { label: "مقاومت", value: "ضدآب IP67" },
      { label: "مکالمه و اینترکام", value: "حدود ۳۲ ساعت" },
      { label: "ضبط ویدئو", value: "حدود ۴ ساعت" },
      { label: "آماده‌به‌کار", value: "تا حدود ۵۰۰ ساعت" },
      { label: "زمان شارژ", value: "حدود ۲.۵ ساعت" },
    ],
    features: [
      "دوربین + اینترکام + هندزفری بلوتوث",
      "فیلم‌برداری 2K",
      "لنز Sony",
      "ارتباط گروهی تا ۶ موتورسوار",
      "اپلیکیشن RICAM",
      "استاندارد IP67",
    ],
    boxContents: [],
    warranty: "",
    shippingStatus: "",
    note: "",
    categories: [helmet, cameraIntercom],
    modified: "2026-09-13T00:00:00.000Z",
  },
];
